### ISSUE TITLE
WHAT IS IT FROM CHROME OS FLEX PENGUIN LINUX 

### ISSUE THREAD

**Issue by CKanerz** [GuallaGang508/SMSBotBypass#17]
Logged in as SMS OTP BYPASS BOT DEV#2798!
/home/willykane9908/SMSBotBypass/bots/discord/commands/secret.js:45
    const member = m.message.guild.member(user);
                                   ^

TypeError: Cannot read property 'member' of null
    at module.exports (/home/willykane9908/SMSBotBypass/bots/discord/commands/secret.js:45:36)
    at Statement.<anonymous> (/home/willykane9908/SMSBotBypass/bots/discord/bot.js:125:9)
    at Statement.replacement (/home/willykane9908/SMSBotBypass/bots/discord/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.replacement (/home/willykane9908/SMSBotBypass/bots/discord/node_modules/sqlite3/lib/trace.js:25:27)

**Comment by CKanerz** [comment]
I can share u my discord link I while try with an other device sorry for my bad English from ckanerz I need to try an other way to make this script run, I want to check something with that I study the domain so.. from my Chromebook OS Flex from a no stock laptop for that and the dev mode missing.. the way to enable it on this laptop.. no way.. for the moment.. But I can make the bot of your script run but when I want to change something it crash in the penguin is the first code I share .. RIP I continue my searching for this script thanks is a great share !

**Comment by kamblegovind** [comment]
🤣😅🙈

**Comment by CoreLine76** [comment]
https://github.com/CoreLine76/OTP-BYPASS-and-SMS-BOT-V-3
